        name: Generate Snake

        on:
          schedule:
            - cron: '0 0 * * 0' # Run every Sunday at midnight UTC
          workflow_dispatch:

        jobs:
          build:
            runs-on: ubuntu-latest
            steps:
              - name: Checkout repository
                uses: actions/checkout@v3
              - name: Generate Snake
                uses: Platane/snk@v3.2.0
                with:
                  github_user_name: YOUR_USERNAME
                  palette: "github"
                  color_snake: "29bbff"
                  color_dots: "a48181, a48181, a48181"
              - name: Commit changes
                uses: stefanproci/git-commit-action@v0
                with:
                  COMMIT_MESSAGE: "Update snake"
                  BRANCH: main
